### ISSUE TITLE
near_to( ) takes literal numbers but not variables

### ISSUE THREAD

**Issue by darenw** [jimporter/mettle#13]
Is this a bug or am I doing this wrong?   Many of the resulting values in our tests will be 1/sqrt(2) or similar constants, for which I have defined constants.  Trouble, near_to_abs() works fine only with explicit number like 123.45, not variables of const double type (or just double).  I'm working in a subsuite within a suite, unsure if it's something to do with [=] captures.  

It doesn't matter if I use near_to( ) or near_to_abs( ).

I tried moving the "sq" variable definition to inside the suite, but the result is the same. I've tried defining other variable names, toying with where they are and how to capture them in the lambdas, but I have not yet guessed the right combination.

SOURCE CODE   ut.buggy-array.cpp

```
// How to check an array using constants from outside the test lambda?
//
//     g++ -g -o ut  ut.buggy-array.cpp  --std=c++14

#include <mettle.hpp>
#if 0
using mettle::near_to;
using mettle::near_to_abs;
using mettle::equal_to;
using mettle::array;
#else
using namespace mettle;
#endif

// A heavily used constant, expected in many results of tests
const double sq = 1.0 / sqrt(2.0);

mettle::suite<>  TestThis("xxx",  [=](auto &_)   {

    const double ep = 1E-6;
    
    _.subsuite("QQQ",  [=](auto &_)   {
        
        _.test("X90",  [=]()   {
            double Q[4];
        
            // Function under test ... faked for bug finding
            Q[0]=Q[1]=Q[2]=Q[3] = 1.6;
            
/*OK */     expect(Q, array( near_to(6.6,2.2), near_to(6.6,2.2), near_to(6.6,2.2), near_to(6.6,2.2) ));
/*BAD*/     expect(Q, array( near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2) ));
/*OK */     expect(Q, array( near_to(6.6,ep), near_to(6.6,ep), near_to(6.6,ep), near_to(6.6,ep) ));
/*BAD*/     expect(Q, array( near_to(sq,ep), near_to_abs(sq,ep), near_to_abs(sq,ep), near_to_abs(sq,ep) ));
        }); 
        
    }); // subsuite
}); // suite
```

Compiling results in:
```
> g++ -g  -o ut    ut.buggy-array.cpp  --std=c++14                                                                                 
ut.buggy-array.cpp: In lambda function:
ut.buggy-array.cpp:32:44: error: no matching function for call to 'near_to(const double&, double)'
 /*BAD*/     expect(Q, array( near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2) ));
                                            ^
In file included from /usr/include/mettle/matchers.hpp:7:0,
                 from /usr/include/mettle.hpp:5,
                 from ut.buggy-array.cpp:5:
/usr/include/mettle/matchers/arithmetic.hpp:14:6: note: candidate: template<class T> auto mettle::near_to(T&&, const T&)
 auto near_to(T &&expected, const T &epsilon) {
      ^
/usr/include/mettle/matchers/arithmetic.hpp:14:6: note:   template argument deduction/substitution failed:
ut.buggy-array.cpp:32:44: note:   deduced conflicting types for parameter 'const T' ('const double&' and 'double')
 /*BAD*/     expect(Q, array( near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2) ));
                                            ^
In file included from /usr/include/mettle/matchers.hpp:7:0,
                 from /usr/include/mettle.hpp:5,
                 from ut.buggy-array.cpp:5:
/usr/include/mettle/matchers/arithmetic.hpp:27:13: note: candidate: template<class T> typename std::enable_if<(! std::numeric_limits<_Tp>::is_integer), decltype (mettle::near_to(declval<T>(), declval<T>()))>::type mettle::near_to(T&&)
 inline auto near_to(T &&expected) -> typename std::enable_if<
             ^
/usr/include/mettle/matchers/arithmetic.hpp:27:13: note:   template argument deduction/substitution failed:
ut.buggy-array.cpp:32:44: note:   candidate expects 1 argument, 2 provided
 /*BAD*/     expect(Q, array( near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2), near_to(sq,2.2) ));
                                            ^
```
(This is just the first of several. Errors come four at a time per /*BAD*/ line)

**Comment by darenw** [comment]
As a workaround, we #define the variable name as an explicit number, and comment out its normal "const double" definition.

**Comment by jimporter** [comment]
Thanks for the bug report! I can reproduce the issue, and I have a fix coming shortly. The problem was that the template types for `near_to` and `near_to_abs` were a little too strict.

**Comment by jimporter** [comment]
That should do it, plus some tests so it can't regress. Thanks again!

**Comment by darenw** [comment]
Another workaround: use casts, as in changing near_to(sq,ep) to near_to((double)sp,ep).   But I'll try your fix today.  So far, we're liking Mettle and don't mind a few hiccups along the way as it grows.

**Comment by jimporter** [comment]
Yeah, that workaround will convert `sp` to an rvalue, which will make everything work. The new version resolves that and simplifies some of the code too.

Glad to hear you're having success with mettle! I'm pretty close to releasing 1.0b1, but I desperately needed a break from programming, so I haven't made much progress in the past couple weeks. Once I get version 0.1 of [bfg](https://github.com/jimporter/bfg9000) finished, I'll probably release mettle 1.0b1.
